branches:
  only:
    - master

dist: trusty
sudo: false

language: node_js

node_js:
  - "10"

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - GH_REPO=https://${GH_TOKEN}@github.com/herotc/bfa.herodamage.com.git
    - GH_SOURCE_BRANCH=master
    - GH_TARGET_BRANCH=gh-pages
    - NODE_ENV=production
    - BASE_URL=https://bfa.herodamage.com
    # The number of file changes required to deploy, put the number of files generated on build + 1
    - DEPLOY_THRESHOLD=4

before_install:
  - npm install npm -g # The npm version bundled with node is rarely the latest stable
  - node --version
  - npm --version

before_script:
  - chmod +x ./scripts/ci/build.sh
  - chmod +x ./scripts/ci/deploy.sh
  - ./script/ci/build.sh
  - ./script/ci/deploy.sh
